version: '3.7'

services:
  resgate.nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - resgate

  resgate.resgate:
    image: resgateio/resgate
    command: "--nats nats://resgate.nats:4222"
    ports:
      - "8080:8080"
    depends_on:
      - resgate.nats
    networks:
      - resgate

  resgate.frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: resgate-next
    volumes:
      - ./frontend:/app
    networks:
      - resgate
    depends_on:
      - resgate.resgate

  resgate.app:
    build:
      context: ./
    container_name: resgate-app
    volumes:
      - ./:/opt/app
    networks:
      - resgate
    depends_on:
      - resgate.resgate


networks:
  resgate:
    driver: bridge
